POST http://localhost:3030/auth/login HTTP/1.1
content-type: application/json

{
    "email": "test1@test.com",
    "password": "T3$t@GMT"
}

Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmUwYjIxODVmOWUxYWRlMGZhZDMyNzIiLCJpYXQiOjE3MjYwMDU2NzAsImV4cCI6MTcyNjAwOTI3MH0.-TKLyAdSa7KxloppFfPiBmBfK2G5DeGj67UxCorwsgE